version: '3.8'

services:
  pyspark-jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark-jupyter_hw
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_TOKEN=''  # Пустой токен
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.ip=0.0.0.0
